spring:
  application:
    name: msclientes

server:
  port: 0

eureka:
  client:
    client-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}