spring:
  application:
    name: mscloudgateway
  claud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          lower-case-route-id: true
  security:
    auth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/mscourserealm


server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/