spring:
  application:
    name: mscloudgateway
  claud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          lower-case-route-id: true
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/